# Generated by Django 3.2.19 on 2023-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0005_auto_20230621_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindividualdatasourceupload',
            name='error',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='historicalindividualdatasourceupload',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRIGGERED', 'Triggered'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Success'), ('FAIL', 'Fail')], default='PENDING', max_length=255),
        ),
        migrations.AddField(
            model_name='individualdatasourceupload',
            name='error',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='individualdatasourceupload',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRIGGERED', 'Triggered'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Success'), ('FAIL', 'Fail')], default='PENDING', max_length=255),
        ),
    ]
