# Generated by Django 4.2.13 on 2024-09-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_auto_20230925_2243'),
        ('individual', '0016_remove_recipient_from_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='village',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location'),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='village',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location'),
        ),
        migrations.AddField(
            model_name='individual',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        ),
    ]
