# Generated by Django 4.2.10 on 2024-05-31 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "individual",
            "0014_remove_historicalindividualdatasourceupload_individual_and_more",
        ),
        ("individual", "0016_remove_recipient_from_role"),
    ]

    operations = []
