# Generated by Django 4.2.13 on 2024-10-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0017_remove_historicalindividualdatasourceupload_individual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupindividual',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='individual.group'),
        ),
        migrations.AlterField(
            model_name='groupindividual',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='individual.individual'),
        ),
    ]
